import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import usersRouter from "./users";
import sessionsRouter from "./sessions";
import auditRouter from "./audit";
import customersRouter from "./customers";
import locationsRouter from "./locations";
import employeesRouter from "./employees";
import inventoryRouter from "./inventory";
import purchaseRequestsRouter from "./purchase-requests";
import equipmentRouter from "./equipment";
import documentsRouter from "./documents";
import filesRouter from "./files";
import storageRouter from "./storage";
import intakeRouter from "./intake";
import workOrdersRouter from "./work-orders";
import closeoutsRouter from "./closeouts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(usersRouter);
router.use(sessionsRouter);
router.use(auditRouter);
router.use(customersRouter);
router.use(locationsRouter);
router.use(employeesRouter);
router.use(inventoryRouter);
router.use(purchaseRequestsRouter);
router.use(equipmentRouter);
router.use(documentsRouter);
router.use(filesRouter);
router.use(storageRouter);
router.use(intakeRouter);
router.use(workOrdersRouter);
router.use(closeoutsRouter);

export default router;
