import { integer, jsonb, pgTable, text, timestamp } from "drizzle-orm/pg-core";
import { createInsertSchema } from "drizzle-zod";
import { randomUUID } from "node:crypto";
import { z } from "zod/v4";
import { tenantsTable } from "./tenants";

// RoseOS recommendations are generated by the backend rules service from live
// tenant data — never hardcoded seed text. Each row records the rule that fired,
// the evidence behind it, and its human-in-the-loop lifecycle state.
export const recommendationStatuses = [
  "Open",
  "Approved",
  "Edited",
  "Rejected",
  "Snoozed",
  "Resolved",
] as const;
export type RecommendationStatus = (typeof recommendationStatuses)[number];

export const recommendationSeverities = ["info", "warning", "urgent"] as const;
export type RecommendationSeverity = (typeof recommendationSeverities)[number];

export interface RecommendationEvidence {
  label: string;
  value: string;
}

export interface RecommendationLifecycleEvent {
  at: string;
  actorId: string;
  actor: string;
  action: string;
  detail: string;
}

export const recommendationsTable = pgTable("recommendations", {
  id: text("id")
    .primaryKey()
    .$defaultFn(() => randomUUID()),
  tenantId: text("tenant_id")
    .notNull()
    .references(() => tenantsTable.id),
  // Stable key derived from the rule + source entity so a regenerated
  // recommendation for the same condition updates in place (and disappears when
  // the underlying condition resolves).
  dedupeKey: text("dedupe_key").notNull(),
  ruleKey: text("rule_key").notNull(),
  type: text("type").notNull(),
  severity: text("severity").notNull(),
  title: text("title").notNull(),
  description: text("description").notNull(),
  reason: text("reason").notNull(),
  evidence: jsonb("evidence")
    .$type<RecommendationEvidence[]>()
    .notNull()
    .default([]),
  confidence: integer("confidence").notNull().default(0),
  suggestedAction: text("suggested_action").notNull(),
  relatedEntityType: text("related_entity_type"),
  relatedEntityId: text("related_entity_id"),
  status: text("status").notNull().default("Open"),
  // If a human edited the recommendation, the override text lives here.
  editedTitle: text("edited_title"),
  editedDescription: text("edited_description"),
  assignedToUserId: text("assigned_to_user_id"),
  snoozeUntil: timestamp("snooze_until", { withTimezone: true }),
  resolvedByUserId: text("resolved_by_user_id"),
  resolvedAt: timestamp("resolved_at", { withTimezone: true }),
  lifecycle: jsonb("lifecycle")
    .$type<RecommendationLifecycleEvent[]>()
    .notNull()
    .default([]),
  lastGeneratedAt: timestamp("last_generated_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  createdAt: timestamp("created_at", { withTimezone: true })
    .notNull()
    .defaultNow(),
  updatedAt: timestamp("updated_at", { withTimezone: true })
    .notNull()
    .defaultNow()
    .$onUpdate(() => new Date()),
});

export const insertRecommendationSchema = createInsertSchema(
  recommendationsTable,
).omit({ createdAt: true, updatedAt: true });
export type InsertRecommendation = z.infer<typeof insertRecommendationSchema>;
export type Recommendation = typeof recommendationsTable.$inferSelect;
